### ISSUE TITLE
Missing data for hardcoded local paths

### ISSUE THREAD

**Issue by portega-inbrain** [neuromodulation/ECoG_vs_STN#1]
Hello! I'm testing this repo to reproduce some figures but I found some local paths and the notebooks fail to run. 
I understand the data has to be downloaded and that works fine once I change the path. But there are other local paths for which I dont find a reference on what data source to download. 
For now I have found this in:
`PLT_SUPPLEMENTS_PATH = r'C:\Users\ICN_admin\Documents\ECOGVSTN\plot supplements'` in `ECoG_vs_STN\Figure 1\Electrode Plot\All electrode Cortex + STN.ipynb`

Any help would be appreciated! Thanks!

**Comment by marinasaizalia** [comment]
Hi!! I have the same issue as Pablo. I was trying to reproduce one of the subfigures in Figure 1 and it would be great to have the precomputed patient_concat.json with the channels:

    out_path = r'C:\Users\ICN_admin\Documents\ECOGVSTN\data\f_band_features_concatenated\LM_100ms\\'
    with open(out_path+'sub_'+subject_id_+'_patient_concat.json', 'r') as fp:
        dict_ch = json.load(fp)

Thanks!

**Comment by timonmerk** [comment]
Thanks for the interest in this paper! Some of the meta-files were not uploaded, due to size issues. For example the LM_100ms up to 1000ms were all features for all channels. I will check if it's possible to upload it via the eLife interface.

One other caveat is that most of the code generating features was heavily adapted, improved and extended. The new repo for that is this one: https://github.com/neuromodulation/py_neuromodulation 

@marinasaizalia if you want I can send the patient_concat.json or try to share it with google drive for example. You can write me an email at timon.merk@charite.de in case you're interested in that.

@portega-inbrain the .mat files necessary for plotting can be found in this folder: https://github.com/neuromodulation/py_neuromodulation/tree/main/py_neuromodulation/plots Feel free to reach out as well. I am sorry for the inconvenience!

**Comment by portega-inbrain** [comment]
Thanks for your reply @timonmerk. We'll send you an email! :)
